### ISSUE TITLE
i want some dateset to try

### ISSUE THREAD

**Issue by lyuic** [thiagomarquesrocha/siameseQAT#4]
dear sir，i think this idea is very good，if can uploads eclipse，openoffice and so on dateset

**Comment by thiagomarquesrocha** [comment]
> dear sir，i think this idea is very good，if can uploads eclipse，openoffice and so on dateset

Hello @lyuic , thanks for your suggestion, I have uploaded here [Google Drive](https://drive.google.com/file/d/1reRGkmSItk0MJyiefbIjEAEfujAg7JDk/view?usp=sharing) the dataset normalized ready to be processed. In another hand, If you need the raw data check [Alazar page](http://alazar.people.ysu.edu/msr14data/) where I have extracted the dataset. 

I hope that can help you.
